version: '3'

services:
  # Frontend Service
  frontend:
    build:
      context: ./angular-client  # Path to the directory containing the frontend Dockerfile
    ports:
      - "8080:80"  # Expose frontend on port 8080
    environment:
      - API_ENDPOINT='http://localhost:3000'  # Assuming your backend runs on port 3000

  # Backend Service
  backend:
    build:
      context: ./server  # Path to the directory containing the backend Dockerfile
    ports:
      - "3000:3000"  # Expose backend on port 3000
    depends_on:
      - frontend  # Ensure frontend service is running before starting the backend
    command: node index.js  # Specify the command to run the backend application
