apiVersion : apps/v1
kind: Deployment
metadata:
  name: frontenddeployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontendcontainer
          image: hawcr.azurecr.io/frontned
          ports:
          - containerPort: 80
          imagePullPolicy: Always