apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backendcontainer
          image: hawcr.azurecr.io/backned
          ports:
            - containerPort: 8080
            - containerPort: 8085
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backendconfig