apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: socketio-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: socketio
      port: 8085
      targetPort: 8085
  type: LoadBalancer